version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: market_postgres
    restart: always
    environment:
      POSTGRES_USER: market_admin
      POSTGRES_PASSWORD: market_password
      POSTGRES_DB: market_pathways
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
